image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

run:
  script:
    - pip3 install -r requirements.txt
    - python3 generate.py > charlas-nerdearla.ics
  artifacts:
    paths:
      - charlas-nerdearla.ics
